name: model-credit-mlflow
on: [ push ]
jobs:
  run:
    runs-on: [ ubuntu-latest ]
    container: https://github.com/iterative/cml/blob/master/Dockerfile
    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          mlflow run .
          echo "## Model metrics" > report.md
          cat ./evaluate/metrics.txt >> report.md
          echo "## Confusion Matrix Test Dataset" >> report.md
          cml-publish ./evaluate/img/confusion_matrix.png --md >> report.md
          cml-send-comment report.md
